from client.uc.enums.enums import UcSubtypes, UcTypes
from client.uc.resources import (
    AgentCluster,
    Bundle,
    BusinessService,
    Calendar,
    Credential,
    CustomDay,
    DbConnection,
    EmailConnection,
    EmailTemplate,
    OAuthClient,
    PeopleSoftConnection,
    SapConnection,
    Script,
    SnmpManager,
    Task,
    Trigger,
    UnixAgentCluster,
    UnvEventTemplate,
    UnvTemplate,
    Variable,
    VirtualResource,
    WindowsAgentCluster,
    Workflow,
)

TYPE_CLASS_MAPPER = {
    UcTypes.TASK.value: Task,
    UcTypes.TRIGGER.value: Trigger,
    UcTypes.VARIABLE.value: Variable,
    UcTypes.VIRTUAL_RESOURCE.value: VirtualResource,  #
    "virtual": VirtualResource,  # virtual or virtualresource based on the response
    UcTypes.BUNDLE.value: Bundle,
    UcTypes.BUSINESS_SERVICE.value: BusinessService,
    UcTypes.AGENT_CLUSTER.value: AgentCluster,
    UcTypes.CALENDAR.value: Calendar,
    UcTypes.CUSTOM_DAY.value: CustomDay,
    UcTypes.EMAIL_TEMPLATE.value: EmailTemplate,
    UcTypes.SCRIPT.value: Script,
    UcTypes.DB_CONNECTION.value: DbConnection,
    UcTypes.EMAIL_CONNECTION.value: EmailConnection,
    UcTypes.PEOPLESOFT_CONNECTION.value: PeopleSoftConnection,
    UcTypes.SAP_CONNECTION.value: SapConnection,
    UcTypes.SNMP_MANAGER.value: SnmpManager,
    UcTypes.WORKFLOW.value: Workflow,
    UcSubtypes.WINDOWS_AGENT_CLUSTER.value: WindowsAgentCluster,
    UcSubtypes.UNIX_AGENT_CLUSTER.value: UnixAgentCluster,
    UcSubtypes.OUTGOING_EMAIL_CONNECTION.value: EmailConnection,
    UcSubtypes.INCOMING_EMAIL_CONNECTION.value: EmailConnection,
    UcTypes.CREDENTIAL.value: Credential,  # other endpoint return the uc type as credential
    UcTypes.CREDENTIALS.value: Credential,  # /resources/workflow/ return the uc type as credentials
    UcTypes.OAUTH_CLIENT.value: OAuthClient,
    UcTypes.UNV_TEMPLATE.value: UnvTemplate,
    UcTypes.UNV_EVENT_TEMPLATE.value: UnvEventTemplate,
}

UC_DELETE_DEPENDENCY_ORDER = [
    UcTypes.BUNDLE.value,
    UcTypes.TRIGGER.value,
    UcTypes.WORKFLOW.value,
    UcTypes.TASK.value,
    UcTypes.VIRTUAL_RESOURCE.value,
    UcTypes.VARIABLE.value,
    UcTypes.SCRIPT.value,
    UcTypes.PEOPLESOFT_CONNECTION.value,
    UcTypes.SAP_CONNECTION.value,
    UcTypes.DB_CONNECTION.value,
    UcTypes.CALENDAR.value,
    UcTypes.CUSTOM_DAY.value,
    UcTypes.AGENT_CLUSTER.value,
    UcTypes.SNMP_MANAGER.value,
    UcTypes.EMAIL_TEMPLATE.value,
    UcTypes.EMAIL_CONNECTION.value,
    UcTypes.BUSINESS_SERVICE.value,
    UcTypes.CREDENTIAL.value,
]

SUBTYPE_MAPPER = {
    # Tasks
    "sleep": "Timer",
    "timer": "Timer",
    "unix": "Unix",
    "windows": "Windows",
    "ftp": "File Transfer",
    "zos": "Zos",
    "ucmd": "Universal Command",
    "manual": "Manual",
    "sql": "SQL",
    "storedproc": "Stored Procedure",
    "email": "Email",
    "webservice": "Web Service",
    "recurring": "Recurring",
    "ftpfilemonitor": "Remote File Monitor",
    "monitor": "Task Monitor",
    " monitor": "Task Monitor",  # handles the extra space that comes from Bundle Report
    "filemonitor": "Agent File Monitor",
    "systemmonitor": "System Monitor",
    "variablemonitor": "Variable Monitor",
    "emailmonitor": "Email Monitor",
    "universalmonitor": "Universal Monitor",
    "sap": "SAP",
    "workflow": "Workflow",
    "universal": "Universal",
    # Agent Clusters
    "unixagentcluster": "Unix Agent Cluster",
    "windowsagentcluster": "Windows Agent Cluster",
    # Connections
    "databaseconnection": "Database Connection",
    "emailconnection": "Email Connection",
    "peoplesoftconnection": "Peoplesoft Connection",
    "sapconnection": "Sap Connection",
    "snmpmanager": "SNMP Manager",
    # Virtual Resources
    "renewable": "Renewable",
    "boundary": "Boundary",
    "depletable": "Depletable",
    # Script
    "data": "Data",
    "script": "Script",
    "sap definition": "Sap Definition",
    "udm script": "UDM Script",
    "web service payload": "Web Service Payload",
    # Credentials
    "resolvable": "Resolvable",
    "standard": "Standard",
    "web service": "Web Service",
    # email type is the same as tasks
    # Email Connections:
    "outgoing": "Outgoing",
    "incoming": "Incoming",
    # Triggers
    "vm": "Variable Monitor",
    "ap": "Application Monitor",
    "um": "Universal Monitor",
    "em": "Email Monitor",
    "tm": "Task Monitor",
    "fm": "Agent File Monitor",
    "temp": "Temporary",
    "cron": "Cron",
    "time": "Time",
    "composite": "Composite",
    # manual type is the same as tasks
}
